#! /bin/sh
local_dir=
remote_dir=/storage/sdcard1/Downloads
verbose=true

set -e
cleanup() {
	rc=$?
	test "$TD" && rm -r -- "$TD"
	test $rc = 0 || echo "$0 failed" >& 2
}
trap cleanup 0
trap 'exit $?' HUP INT TERM QUIT

checkbox=x
while getopts dqR:L: opt
do
	case $opt in
		d) checkbox=' ';;
		q) verbose=false;;
		L) local_dir=$OPTARG;;
		R) remote_dir=$OPTARG;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

if test "$local_dir"
then
	test -d "$local_dir"
fi
case $remote_dir in
	/*) ;;
	*) false || exit
esac
command -v adb > /dev/null

flist() {
	echo "[$checkbox] $1"
}

rline() {
	IFS=$lf read -r $1 || return
	eval "$1=\${$1%\"\$cr\"}"
	#echo "just read into variable \$$1:"
	#eval printf '%s' "\$$1" | hexdump -C
}

qstr() {
	printf '%s\n' "$*" | sed 's|'\''|'\'\\\\\'\''|g; s/.*/'\'\&\''/'
}

# $1 options; $2 ...: path named
als() {
	local t a
	a=$1; shift
	t=
	while test $# != 0
	do
		t=$t${t:+ }`qstr "$1"`
		shift
	done
	adb shell "ls${a:+ }$a $t"
}

rlist() {
	local st entry nlv dir
	nlv=${2-0}; dir=$TD/dir$nlv; nlv=`expr $nlv + 1`
	#echo examine:
	#printf '%s' "$1" | hexdump -C
	st=`als -ld "$1"`
	#echo result:
	#printf '%s' "$st" | hexdump -C
	case $st in
		[dl]*)
			als "" "$1" > "$dir"
			while :
			do
				case $st in
					l*) ;;
					*) break
				esac
				# Assume that a symlink which is not a
				# directory will list something else than
				# just its own name as the only output.
				{
					rline entry
					test "$entry" != "$1" && break
					rline entry && break
				} < "$dir"
				# Symlink is most likely not a directory.
				# Make sure, though.
				entry=$1/$entry
				case `als -ld "$entry"` in
					[-dl]*) rlist "$entry" $nlv;;
					*) flist "$1"
				esac
				return
			done
			# Directory or a symlink to one.
			while rline entry
			do
				rlist "$1/$entry" $nlv
			done < "$dir"
			;;
		-*) flist "$1";;
		*) false || exit
	esac
}

cr=`printf '\015:'`; cr=${cr%:}
lf=`printf '\012:'`; lf=${lf%:}
adb start-server > /dev/null
case $# in
	0)
		# No arguments? Just emit listing with D/L selections.
		TD=`mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`
		rlist "$remote_dir" > "$TD"/listing # Let errors abort.
		sort -- "$TD"/listing # Only if no error.
		;;
	1)
		# 1 argument? It must be a D/L selection list then.
		test -f "$1"
		exec < "$1"
		cd "$local_dir"
		while IFS= read -r entry
		do
			loc=${entry#"[x] $remote_dir/"}
			test "$loc" = "$entry" && continue
			if $verbose
			then
				echo "Fetching '$loc' from '$remote_dir'" >& 2
			fi
			mkdir -p -- `dirname -- "$loc"`
			adb pull "$remote_dir/$loc" "$loc"
		done
		adb kill-server > /dev/null
		;;
	*) false || exit
esac
