#! /bin/sh
# Watch the current directory for .html files which can be updated by asciidoc
# from corresponding .txt files.
#
# Version 2019.153
# Copyright (c) 2019 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

die() {
	printf '%s\n' "$*" >& 2
	false || exit
}

for bb in busybox-pbyqxzl1ktqlk3fjm3arlrclg busybox-localsite busybox false
do
	command -v $bb > /dev/null 2>& 1 && break
done
test $bb != false || die "BusyBox needs to be installed!"

applet=inotifyd
$bb $applet --help > /dev/null 2>& 1 \
|| die "Locally installed $bb does not provide the '$applet' applet!"

command -v asciidoc > /dev/null 2>& 1 || die "asciidoc is not installed!"

is_newer() {
	local f
	case $1 in
		-*) f=./$1;;
		*) f=$1
	esac
	test `find -H "$f" -newer "$2" | wc -l` = 1 || return
}

convert() {
	echo
	echo "`
		date +'%Y-%m-%d %H:%M:%S'
	` \"$1\" has changed and is being converted..."
	asciidoc "$1"
	echo "`date +%M:%S` \"$2\" has been updated."
}

tr '\n' ' ' << === | sed 's/   */\n\n/g; $!b; p; s/.*//' | fold -sw66
"$bb $applet" is watching directory "`pwd`" for changed .txt files for which
an associated .html file exists.

It will then run asciidoc to update the associated .html files automatically.

Press [Ctrl]+[c] to stop watching the directory.
===
$bb $applet - .:w | {
	ht=`printf '\t:'`; ht=${ht%:}
	while IFS=$ht read -r f f f
	do
		case $f in *.txt)
			h=${f%.*}.html
			test -f "$h" || continue
			is_newer "$f" "$h" && convert "$f" "$h"
		esac
	done
}
