#! /bin/sh
set -e
UUID=l3v9678vdw9y0fzaiklv0puyr

mkd() {
	test -d "$1" && return
	local d=${1%/*}
	test x"$1" = x"$d" && return
	mkd "$d"
	mkdir "$1"
}

trap 'test $? = 0 || echo "Failed!" >& 2' 0

d=${0##*/}_${UUID}
if test -z "$XDG_RUNTIME_DIR"
then
	XDG_RUNTIME_DIR=${TMPDIR:-/tmp}/`id -un`-$d
	d=$XDG_RUNTIME_DIR
else
	d=$XDG_RUNTIME_DIR/$d
fi
if ! test -d "$XDG_RUNTIME_DIR"
then
	mkd "$XDG_RUNTIME_DIR"
	chgrp `id -g` "$XDG_RUNTIME_DIR"
	chmod 700 "$XDG_RUNTIME_DIR"
fi

mkd "$d"
cd "$d"
test $# = 1 && exec dtach -A "$1" -e ^a -z "${SHELL:-bash}"
ls -1
