#! /bin/sh
# Increment the version number and update the copyright ending year if
# necessary.
#
# Specify a list of source files as arguments, or feed a single source file
# as standard input.
#
# Version 2023.211
# Copyright (c) 2016-2023 Guenther Brunthaler. All rights reserved.
# 
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
cleanup() {
	rc=$?
	test "$NF" && rm -f -- "$NF"
	test "$T" && rm -f -- "$T"
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
NF=
T=
trap cleanup 0
trap 'exit $?' HUP INT TERM QUIT

process() {
	awk -v file="$1" -v day="$day" -v year="$year" '
		function qf(msg) {
			return msg " in file \"" file "\""
		}
		
		function info(msg) {
			print msg > "/dev/stderr"
		}

		function die(msg) {
			info(qf(msg) "!")
			exit 1
		}
		
		function update(what) {
			info("Updating " qf(what) "...")
		}
		
		#function report(k, v) {
		#	info(k " == >>>" v "<<<.")
		#}
		
		function parse(text, ere) {
			rest= text
			return mnx(ere)
		}
		
		function mnx(ere) {
			if (match(rest, ere)) {
				mt= substr(rest, 1, RSTART - 1 + RLENGTH)
				rest= substr(rest, RSTART + RLENGTH)
			}
			return RSTART
		}
		
		function splitA(str, arr, sep) {
			return arr[0]= split(str, arr, sep)
		}
		
		function joinA(arr, sep,   i, n, r) {
			n= arr[0]
			r= arr[1]
			for (i= 2; i <= n; ++i) r= r sep arr[i]
			return r
		}
		
		BEGIN {
			ws="[[:space:]]"; ows= ws "*"; ws= ws "+"
			bow= "(^|[^[:alnum:]])"
			crx="([(][Cc][)]|\302\251)"
			crx="([Cc]opyright(ed)?" ows ")?" crx
			crx= "(" crx "|[Ww]ritten)"
			rx= "(in|by" ws "[-_@ .[:alpha:]]+)"
			crx= bow "(" crx "(" ws rx ")?)" ws
			vrx= bow "[Vv]ersion" ws
			integer= "(0|[1-9][0-9]*)"
			vnrx= "^" integer "([.]" integer ")*"
			ynrx= "((19|2[0-9])[0-9]{2})"
		}
		
		{dopr= 1}
	
		parse($0, crx) {
			pfx= mt
			sy= ""; if (mnx("^" ynrx)) sy= mt
			sep= ""
			if (sy != "" && mnx("^" ows "--?" ows)) {
				sep= mt
			}
			ey= "";	if (sep != "" && mnx(ynrx)) ey= mt
			if (sy != "" && rest != "" && rest ~ /^[0-9]/) {
				die("Missing valid copyright end year")
			}
			if (sy != "" && ey == "") ey= sy
			if (sy != "" && sy > ey) {
				die( \
					"copyright start year " sy \
					" was greater than end year " ey \
				)
			}
			if (sy != "" && ey != year) {
				if (year < ey) die( \
					"new copyright end year " year \
					" would become less then current" \
					" end year " ey \
				)
				update( \
					"copyright end year from " \
					ey " to " year \
				)
				ey= year
			}
			if (sy != "") {
				if (sy == ey) ey= sep= ""
				else if (sep == "") sep= " - "
			}
			if (sy != "") {
				print pfx sy sep ey rest
				dopr= 0
			}
		}
		
		parse($0, vrx) {
			pfx= mt
			if (mnx(vnrx)) {
				n= splitA(mt, v, "[.]")
				if ( \
					n >= 2 && v[y= n - 1] >= 2000 \
					&& v[y + 1] >= 1 && v[y + 1] <= 366 \
					|| n >= 3 && v[y= n - 2] >= 2000 \
					&& v[y + 1] >= 1 && v[y + 1] <= 366 \
					&& v[y + 2] >= 1 \
				) {
					t= "year.day_number[.increment]-based"
					if (v[y] > year) die( \
						"Cannot increment " t \
						" version number: old year " \
						v[y] " was already later" \
						" than current year " year \
					); else if ( \
						v[y] == year \
						&& v[y + 1] > day \
					) die( \
						"Cannot increment " t \
						" version number: old day" \
						" number " v[y + 1] \
						" was already later" \
						" than current day" \
						" number " day \
					); else if ( \
						v[y] != year \
						|| v[y + 1] != day \
					) {
						# New year/day and no <inc>.
						v[y]= year; v[y + 1]= day
						if (n == y + 2) v[0]= --n
					} else {
						# Create or increment <inc>.
						if (n == y + 1) {
							v[v[0]= ++n]= 0
						}
						++v[n]
					}
				} else if (v[n] >= 0) {
					t= "serially incrementing"
					++v[n] # Increment last component.
				} else t= ""
				if (t != "") {
					nv= joinA(v, ".")
					update( \
						t " version number from " mt \
						" to " nv \
					)
					print pfx nv rest
					dopr= 0
				}
			}
		}

		dopr {print}
	'
}

year=`date -u +%Y.%j | sed 's/[.]0*/./'`
day=${year#*.}; year=${year%%.*}
mode=`umask -S`
T=`mktemp "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`
if test $# = 0
then
	process "(standard input)"
else
	for file
	do
		test -f "$file"
		test -r "$file"
		process "$file" < "$file" > "$T"
		if cmp -s -- "$file" "$T"
		then
			:
		else
			echo "Updating $file..." >& 2
			NF=`mktemp -- "$file.XXXXXXXXXX"`
			cat "$T" > "$NF"
			chmod "$mode" -- "$NF"
			for perm in x w
			do
				if test -$perm "$file"
				then
					chmod +$perm -- "$NF"
				else
					chmod -$perm -- "$NF"
				fi
			done
			if test ! -w "$file"
			then
				echo "Updated file '$NF'" \
					"shall replace '$file'."
				echo "The old '$file' needs to removed first."
				echo "But '$file' is write-protected."
			fi >& 2
			rm -- "$file" # User might choose to *not* remove.
			nf=$NF
			test ! -f "$file" && NF=
			mv -- "$nf" "$file"; NF=
		fi
	done
fi
