#! /usr/bin/perl -w
#
# Create hardlinks for all tools provided by the
# BusyBox executable which can be found in the
# current directory or $PATH.
#
# The hardlinks will be created in the current
# directory. Already existing files will be
# skipped.
#
# Version 2023.365
# Copyright (c) 2006-2023 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.


use strict;
substr($ENV{PATH}, 0, 0)= '.:';
my $bb= qx/command -v busybox | head -1/ or die "Could not locate BusyBox";
chomp $bb;
die "'$bb' is not executable" unless -x $bb;
open IN, qq'"$bb" --help |' or die "Cannot get $bb --help";
my $n= 0;
my $s;
while (defined($_= <IN>)) {
   if ($s) {
      chomp;
      foreach (grep $_, split /,\s*|^\s*/s) {
         if (-e $_) {
            warn "Not creating '$_' - already exists";
         } else {
            if (link $bb, $_ or symlink $bb, $_) {
               ++$n
            } else {
               warn "Could not link '$bb' to '$_': $!";
            }
         }
      }
   } elsif (/defined functions:\s*$/) {
      $s= 1;
   }
}
close IN or die;
print "$n links have been created.\n";
