#! /bin/sh
exec 5>& 1 > /dev/null; test -t 5 && exec >& 5
echo "Currently exported CFLAGS, MAKEFLAGS etc:"
echo
f='AS C CPP CXX LD MAKE'
export -p | grep -E "^export (`echo $f | tr ' ' '|'`)FLAGS=" \
| {
	cut -d ' ' -f 2-
	for f in $f
	do
		echo "${f}FLAGS@"
	done
} | skip= LC_COLLATE=C sort \
| while IFS= read -r line
do
	case $line in
		*=*) echo export "$line"; skip=${line%%=*};;
		"${skip}@") ;;
		*) echo unset ${line%"@"}
	esac >& 5
done
#export -p | grep -E '^export (AS|C|CPP|CXX|LD|MAKE)FLAGS=' >& 5
echo
echo "(Hint: Redirect this output into a script file and source it later.)"
