#! /bin/sh


die() {
	echo "ERROR: $*" >& 2
	false; exit
}


run() {
	"$@" && return
	die "Could not execute >>>$*<<<: return code ${?}!"
}


system() {
	REPLY=`run "$@"` || exit
}


test $# = 0 && set -- .
system date +%s; MARKER=${REPLY}_$$
set -- "$@" "$MARKER"
for D
do
	test x"$D" = x"$MARKER" && break
	run test -d "$D"
	system readlink -f "$D"
	set -- "$@" "$REPLY"
done
while test x"$1" != x"$MARKER"
do
	shift
done
shift
while :
do
	system tempfile; T=$REPLY
	rm "$T"
	mkdir -m 700 "$T" && break
done
trap "cd; rm -rf --one-file-system '$T'" 0
run cd "$T"
run find-c-and-cpp-sources-files "$@" > cscope.files
run cscope -q
