#! /bin/sh
# List the cummulative sizes of all executables specified on the command line
# and all their shared library dependencies. If executables do not specify any
# pathname prefix, they will be searched in $PATH. Any duplicates in the
# resulting list of files will be removed before calculating the total.
#
# Version 2021.39
#
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0
list=0
while getopts l opt
do
	case $opt in
		l) list=1;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`
for x
do
	case $x in
		*/*) ;;
		*) x=`command -v -- "$x"`
	esac
	case $x in
		-*) x=./$x
	esac
	test -x "$x" || exit
	printf '%s\n' "$x"
	ldd "$x" | sed '
		s/.* => //; t1
		s|^[[:space:]]*\(/[^(]\{1,\}[^[:space:]] (\)|\1|; t1; d
		:1; s/ ([^)]*)$//; t; d
	'
done \
| xargsL ls -Logn -- \
| {
	S='[^[:space:]]\{1,\}'; f='[[:space:]]\{1,\}'$S
	sed "s/^$S$f\($f\)$f$f$f/\\1/"
} \
| sort -u -k 2 \
| awk '
	{
		s+= $1
		if ('$list') print
	}
	END {
		if (s < 1e6) {
			printf "%u Bytes\n", s
		} else {
			printf "%.1f MB\n", s / 1000 ^ 2
		}
	}
'
