#!/usr/bin/perl
#
# $HeadURL: /caches/xsvn/trunk/usr/local/bin/configsync $
# $Author: root $
# $Date: 2006-08-27T09:44:37.131062Z $
# $Revision: 289 $


srand time;
my $randletter= "(int (rand (26)) + (int (rand (1) + .5) % 2 ? 65 : 97))";
my $salt= sprintf ("%c%c", eval $randletter, eval $randletter);
my $user= @ARGV > 1 ? shift() . ":" : "";
my $plaintext= shift;
my $crypttext= crypt ($plaintext, $salt);
print "$user${crypttext}\n";
