#! /bin/sh

# Without arguments, show all resolved symlinks in /dev, allowing "grep" to
# detect aliases.
#
# If arguments are given, "/dev/" will be prepended to them except to those
# which already have this prefix. Then the resulting arguments must be paths
# or symlinks into /dev, and only symlink aliases of thoses paths will be
# shown.
#
# An argument like "8:5" will be transformed into both "/dev/block/8:5" and
# "/dev/char/8:5", which allows searching for particular block and character
# devices quickly.
#
# Version 2023.132.2
# Copyright (c) 2023 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

if test $# != 0
then
	i=$#
	while :
	do
		case $1 in
			/dev/*) set -- "$@" "$1";;
			*)
				if
					expr x"$1" \
					: x'[0-9]\{1,\}:[0-9]\{1,\}$' \
					> /dev/null
				then
					set -- "$@" "/dev/block/$1"
					set -- "$@" "/dev/char/$1"
				else
					set -- "$@" "/dev/$1"
				fi
		esac
		shift
		i=`expr $i - 1` || break
	done
	grepargs() {
		sed -f /dev/fd/5 5<< '.'
			s/^^/\\&/
			s/[$]$/\\&/
			s/[[\\*.]/\\&/g
			s/'/'\\''/g
			s|.*|^& // |
			s/.*/-e '&'/
.
	}
	eval set grep `readlink -f -- "$@" | LC_COLLATE=C sort -u | grepargs`
else
	set cat
fi

find /dev ! -type d | while IFS= read -r f
do
	test ! -e "$f" && continue
	r=`readlink -f -- "$f"`
	test "$f" = "$r" && continue
	echo "$r // $f"
done | LC_COLLATE=C sort | "$@"
