#! /bin/sh
# Convert all arguments from degrees fahrenheit into degrees celsius. Without
# any arguments, read values to be converted from standard input instead. Uses
# the current locale's decimal point.
#
# Copyright (c) 2017 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.
set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

convert() {
	local temp frac rest last div
	temp=$1; frac=; div=1
	while test "$temp"
	do
		rest=${temp%?}; last=${temp#"$rest"}
		if test "$last" = "$decimal_point"
		then
			div=1`printf %s "$frac" | tr -c 0 0`
			frac=$rest$frac
			break
		fi
		frac=$last$frac
		temp=$rest
	done
	# round(100 * frac / div)
	# = floor(100 * (5 * frac / div / 9 - 160 ∕ 9) + 0.5)
	if temp=`expr \( 1000 \* $frac - 31991 \* $div \) / \( 18 \* $div \)`
	then
		rest=${temp%??}; frac=${temp#"$rest"}
		temp=$rest$decimal_point$frac
	else
		temp=0
	fi
	$verbose && temp="$1 °F = $temp °C"
	printf '%s\n' "$temp"
}

if test -t 1
then
	verbose=true
else
	verbose=false
fi
while getopts q opt
do
	case $opt in
		q) verbose=false;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

eval `locale -k LC_NUMERIC | grep ^decimal_point=`
: ${decimal_point:=.}

case $# in
	0)
		while read celsius
		do
			convert "$celsius"
		done
		;;
	*)
		for celsius
		do
			convert "$celsius"
		done
esac
