#! /bin/sh
# Version 2018.77
#
# Copyright (c) 2011-2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

die() {
	echo "ERROR: $*" >& 2
	false; exit
}


run() {
	"$@" && return
	die "Could not execute >>>$*<<<: return code ${?}!"
}


NTS=
while getopts 0 OPT
do
	case $OPT in
		0) NTS=Y;;
		*) false; exit;;
	esac
done
shift `expr $OPTIND - 1 || :`
test $# = 0 && set -- .
for D
do
	run test -d "$D"
done
set -- "$@" '(' -regex '.*/\.[^.]+$' -o -name 'CMakeFiles' ')'
set -- "$@" -type d -prune -o
set -- "$@" -iregex '.+\.\([lyC]\|[ch]\(\([xp+]\)\3\)?\|inl\)$' -type f
if test -n "$NTS"
then
	set -- "$@" -print0
else
	set -- "$@" -print
fi
run find "$@"
