#! /bin/sh
exit_version() {
	wr << ===; exit
$APP Version 2026.244
Copyright (c) 2012-2026 Guenther Brunthaler. All rights reserved.

This script is free software.
Distribution is permitted under the terms of the GPLv3.
===
}

exit_help() {
	wr << ===; echo; exit_version
$APP - synthesize local IPv4 addresses from FQDNs as used in the "xworld"
 administrative realm

Without any FQDNs as arguments, uses all FQDNs from /etc/hosts that refer to
 IPv4 addresses in the range reserved for local nets as well as all
 IP-addresses starting with "0.".

The generated Class-A IPv4 addresses from the range reserved for private use
 should be used for classless */16 subnetting.

In particular, the first byte will always be 0x0a, the second byte will be
 mapped from the MD4 hash of the domain-parts of the FQDN, and the final two
 bytes will be mapped from the MD4 hash of the host name part of the FQDN.

Those mappings will map the hashes into the following numeric ranges:

network-range:   0x01 -   0xFE (10.1.x.x - 10.254.x.x)
static-range:  0x0001 - 0xBFFA (10.x.0.1 - 10.x.191.250)
manual-range:  0xBFFB - 0xDFF9 (10.x.191.251 - 10.x.223.249)
dynamic-range: 0xDFFA - 0xFFFE (10.x.223.250 - 10.x.255.254)

Those ranges consist of one or more building blocks of values. Every building
 block contains 1/8th of the total value range (0x0001 to 0xFFFE), rounded
 down, execept for the last block which also contains the remaining values
 lost to the other building blocks due to rounding.

This means the first 7 building blocks contain 0x1FFF values each, while the
 8th building block contains the remaining 0x2005 values.

The static-range will cover the first 6 building blocks, while the
 manual-range will cover the next building block, and the dynamic-range will
 cover the last building block.

The resulting dynamic-range and static-range will be interpreted as 16-bit
 base-256 big-endian integers. Each integer will then be formatted from this
 as two individual bytes, MSB first.

This script only uses the network-range (by hashing the domain-parts) and the
 static-range (by hashing the host name part) in its output.

The dynamic-range is not used and reserved for DHCP or other dynamic
 allocation mechanisms for IP adresses.

The manual-range ist not used either and is reserved for manually-assigned
 IP-adresses (similar to the static-range, but not calculated via hashing by
 THIS utility).

Note that the generated addresses will omit 10.0.x.x/16, 10.255.x.x/16,
 10.x.0.0/16 and 10.x.255.255/16 which represent either the subnets themselves
 or their broadcast-addresses.

Supported options:

-c: Compatibility mode. Emulates the old behaviour before version 2026.243 of
 this utility which did not reserve ranges for DHCP or manually-assigned
 addresses and also used a slower hash algorithm.

-h: show this help and exit

-V: show version information and exit
===
}
APP=${0##*/}

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

wr() {
	{
		unterminated=false
		while IFS= read -r line
		do
			test "${line%" "}" = "$line"
			test "${line#" "}" != "$line" && unterminated=false
			$unterminated && echo
			printf '%s' "$line"
			unterminated=true
		done
		$unterminated && echo
	} | fold -sw $LINEWIDTH
}
LINEWIDTH=`tput cols || echo ${COLUMNS:-66}`

s2uchex() {
	printf '%s' "$1" | openssl $hash -hex | cut -d ' ' -f 2 | tr a-f A-F
}

get_from_etc_hosts() {
	sed -e "
		s,`printf '[\t ]'`\+, ,g
		s,^ *,,
		s, *$,,
	" < /etc/hosts \
	| awk '
		$1 ~ /^[0-9]/ && $2 != "" {
			if ( \
				split($1, ip, "[.]") == 4 && ( \
					ip[1] == 10 \
					|| ip[1] == 127 && ( \
						ip[2] || ip[3] || ip[4] != 1 \
					) \
					|| ip[1] == 0 \
					|| ip[1] == 192 && ip[2] == 168 \
					|| ip[1] == 169 && ip[2] == 254 \
					|| ip[1] == 172 && ( \
						(ip[2] - ip[2] % 16) / 16 \
						== 16 \
					) \
				) \
			) { \
				print $2
			}
		}
	'
}

hash=md4 base=1 modulus=BFFA
while getopts chV opt
do
	case $opt in
		c)
			# Compatibility fallback mode: old behaviour.
			hash=md5 base=1 modulus=FFFE
			;;
		h) exit_help;;
		V) exit_version;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`
for needed in openssl dc
do
	command -v $needed > /dev/null || exit
done
export LC_ALL=C
test $# = 0 && set -- `get_from_etc_hosts`
while :
do
	fqdn=${1:?Usage: ${0##*/} <fqdn> ...}
	host_name=${fqdn%%.*}
	if test "$host_name" = "$fqdn"
	then
		network_name=
	else
		network_name=${fqdn#*.}
	fi
	host_id=`s2uchex "$host_name"`
	network_id=`s2uchex "$network_name"`
	x_y_z=`
		dc -e "
			16 i
			$network_id FE % 1 + n
			[.] n
			$host_id $modulus % $base + d
			100 / n
			[.] n
			100 % n
		"
	`
	printf '10.%s\t%s\n' $x_y_z "$fqdn"
	shift
	test $# = 0 && break
done
