#! /bin/sh

trap 'test $? = 0 || echo "${0##*/} failed!" >& 2' 0
base=1000; suffix=B
while getopts b opt
do
	case $opt in
		b) base=1024; suffix=iB;;
		*) false || exit
	esac
done
sum=0
files=0
others=0
while IFS= read fso
do
	if test -f "$fso" && test ! -L "$fso"
	then
		size=`stat -c %s -- "$fso"`
		sum=`expr $sum + $size`
		files=`expr $files + 1`
	elif test -e "$fso"
	then
		others=`expr $others + 1`
	else
		echo "Ignoring non-existing '$fso'!" >& 2
	fi
done
if test ! -t 1
then
	echo $sum
	exit
fi
sum=${sum}0; factor=1
for u in bytes K M G T P E Z Y bad
do
	test $u != bad
	val=`expr "(" $sum + $factor / 2 ")" / $factor`
	if test $val -lt 10000
	then
		int=${val%?}; fract=${val#"$int"}
		case $u in
			?) sum="$int.$fract $u$suffix";;
			*) sum="$int $u"
		esac
		break
	fi
	factor=`expr $factor "*" $base`
done
echo "$sum in $files files."
test $others = 0 && exit
echo "$others non-file file system objects have been ignored." >& 2
