#! /bin/sh

trap 'test $? = 0 || echo "${0##*/} failed!" >& 2' 0
add=500; div=1000; suffix=B
while getopts b opt
do
	case $opt in
		b) add=512; div=1024; suffix=iB;;
		*) false || exit
	esac
done
sum=0
files=0
others=0
while IFS= read fso
do
	if test -f "$fso" && test ! -L "$fso"
	then
		size=`stat -c %s -- "$fso"`
		sum=`expr $sum + $size`
		files=`expr $files + 1`
	elif test -e "$fso"
	then
		others=`expr $others + 1`
	else
		echo "Ignoring non-existing '$fso'!" >& 2
	fi
done
if test ! -t 1
then
	echo $sum
	exit
fi
sum=${sum}0
for u in bytes K M G T P E Z Y bad
do
	test $u != bad
	if test $sum -lt 10000
	then
		case $u in
			?) u=$u$suffix
		esac
		int=${sum%?}; fract=${sum#"$int"}
		sum=$int
		test $fract != 0 && sum=$sum.$fract
		sum="$sum $u"
		break
	fi
	sum=`expr "(" $sum + $add ")" / $div`
done
echo "$sum in $files files."
test $others = 0 && exit
echo "$others non-file file system objects have been ignored." >& 2
