#! /bin/sh
# Report GCC settings, predefined macros and search paths.
#
# Version 2023.211
# Copyright (c) 2010-2023 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.


fail() {
	local rc=$?
	test "$1" && rc=$1
	test $rc = 0 && { false; rc=$?; }
	test -z "$UNWIND" && exit $rc
	return $rc
}


die() {
	rc=$?
	echo "ERROR: $*" >& 2
	fail $rc
}


cmd_failure() {
	die "Command >>>$1<<< failed with return code $2!"
}


run() {
	"$@" ||	cmd_failure "$*" $?
}


system() {
	REPLY=`UNWIND= run "$@"` || fail
}


UNWIND=
system mktemp "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"; T=$REPLY
trap "rm -- \"$T\"" 0
trap 'exit $?' HUP INT TERM QUIT
run gcc -v -dD -E -x c "$T" 2>& 1 | run less
