#! /bin/sh

# v2025.138
set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

dry_run=false
while getopts n opt
do
	case $opt in
		n) dry_run=true;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

test -e .git # Directory, gitlink or symlink to any of those.
case $0 in
	*-unversioned) f=.git/info/exclude;;
	*-versioned) f=.gitignore;;
	*) false || exit
esac

unknowns() {
	case $# in
		0) git status -s | sed 's|^?? |/|; t; d';;
		*)
			for f
			do
				f=${f%%/}
				case $f in
					. | .. \
					| ./* | ../* \
					| */./* | */../* \
					| */. | */.. \
					| /* | '') false || exit;;
				esac
				if test -L "$f"
				then
					: # Symlinks are allowed.
				elif test -d "$f"
				then
					ls -d -- "$f"/* \
					| while IFS= read -r f
					do
						if test -L "$f" || test -f "$f"
						then
							printf '%s\n' "$f"
						else
							echo "Not adding" \
								"'$f'!" >& 2
						fi
					done
					continue
				else
					# No other kinds of special file
					# allowed in git.
					test -f "$f"
				fi
				printf '%s\n' "$f"
			done \
			| sed 's|^|/|'
	esac
}

msg="Appending unversioned entries to $f..."
if $dry_run
then
	echo "SIMULATION: $msg" >& 2
	unknowns ${1+"$@"}
else
	echo "$msg" >& 2
	unknowns ${1+"$@"} >> "$f"
fi
