#! /bin/sh

# v2025.11
set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

dry_run=false
while getopts n opt
do
	case $opt in
		n) dry_run=true;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

test -d .git
case $0 in
	*-unversioned-*) f=.git/info/exclude;;
	*-versioned-*) f=.gitignore;;
	*) false || exit
esac

unknowns() {
	git status -s | sed 's|^?? |/|; t; d'
}

set -- "Appending unversioned entries to $f..."
if $dry_run
then
	echo "SIMULATION: $*" >& 2
	unknowns
else
	echo "$*" >& 2
	unknowns >> "$f"
fi
