#! /bin/sh
# Copyright (c) 2016 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.
set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
git reflog expire --expire=all --all
git gc --aggressive --prune=all
