#! /bin/sh

# Version 2022.135
# Copyright (c) 2022 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

if test $# != 0
then
	cd -- "$1"; shift
fi
test $# = 0

find . -path './*.git/refs/heads/*' | cut -d / -f 2- \
| sed 's/./\\&/g' | xargs ls -trd --
