#! /bin/sh
exit_version() {
	cat << ===; exit
$APP Version 2021.77
Copyright (c) 2021 Guenther Brunthaler. All rights reserved.

This script is free software.
Distribution is permitted under the terms of the GPLv3.
===
}

exit_help() {
	cat << ===; echo; exit_version
$APP - convert HTML to ASCII text (and any tables to ASCII-art)

Usage: $APP [ <options> ... [--] ] < input.html > output.txt

Supported options:

-w <columns>: Format output with that many columns (default: $default_width)
-h: show this help and exit
-V: show version information and exit
===
}
APP=${0##*/}

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0
default_width=72
width=$default_width
while getopts w:hV opt
do
	case $opt in
		w) width=$OPTARG;;
		h) exit_help;;
		V) exit_version;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

all=true
pkg=
for need in tidy w3m xmlstarlet
do
	case $need in
		*:) pkg=${need%:};;
		*)
			: ${pkg:="$need"}
			command -v -- "${need}" > /dev/null 2>& 1 || {
				echo
				echo "Required utility '$need' is missing!"
				echo "On some systems it can be installed with"
				echo "\$ sudo apt-get install $pkg"
				all=false
			} >& 2
			pkg=
	esac
done
$all || exit

tidy -asxhtml --quote-nbsp no --show-warnings no --show-info no 2> /dev/null \
| xmlstarlet pyx \
| sed '/^Aborder/d; /^(table/!b; p; s/.*/Aborder 1/' \
| xmlstarlet p2x \
| w3m -cols "$width" -O US-ASCII -T text/html -graph
