#!/bin/sh
# Returns 0 if $1 is a mount point
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/is_mountpoint_mounted $
# $Author: root(xvaio) $
# $Date: 2006-08-27T11:02:50.623454Z $
# $Revision: 254 $


/bin/cat /proc/mounts | /usr/bin/cut -d' ' -f 2 | /bin/grep -x $1 > /dev/null
