#! /bin/sh
# Returns 0 if $1 is a mount point
#
# Version 13.85
#
# (c) 2013 by Guenther Brunthaler.
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.


/bin/cat /proc/mounts | /usr/bin/cut -d' ' -f 2 \
| /bin/grep -x "`readlink -f \"$1\"`" > /dev/null
