#! /bin/sh

# 'joe' editor wrapper for hard-wrapped text with tabulation-based indentation
#
# Indentation inserts single horizontal tabulation characters, which are set
# to use the ANSI terminal standard width of 8 columns for the tabulation
# zones of the display.
#
# This is the most human-friendly mode for classic text files intended to be
# read by humans without further reformatting.
#
# Version 2021.39

exec joe -rmargin 66 -wordwrap --flowed --spaces -indentc 9 -istep 1 ${1+"$@"}
