#! /bin/sh

# 'joe' editor wrapper for "format=flowed" e-mail text.
#
# This is the text format used by many mail user agents like Thunderbird when
# composing plain-text (non-HTML) e-mail messages.
#
# It uses "RFC 3676"-style reversible hard word-wrapping ("flow-text"), as
# would be indicated by a MIME type
#
# Content-Type: text/plain; charset=UTF-8; format=flowed
#
# except that the charset may differ. This style puts a space at the end of
# hard-wrapped lines within a paragraph, but not on its last line. This is
# exactly the same format 'fold -sw' produces. It allows to reflow such
# documents safely to a different line width, without screwing up preformatted
# text (because such text will normally not have any spaces at the end of its
# lines).
#
# Version 2020.115

exec joe -rmargin 72 -wordwrap -flowed -spaces -indentc 32 -istep 4 ${1+"$@"}
