#! /bin/sh
# Keeps the "-backpath" setting if there is one defined, and replaces the
# "ftyperc"-inclusion by an inclusion of "~/.joe". Everything else is
# replaced with the skeleton template.
#
# Version 15.214
# Copyright (c) 2012-2015 Guenther Brunthaler. All rights reserved.
# This source file is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "Failed!" >& 2' 0

export LC_ALL=C
s='[[:space:]]'; n='[^[:space:]]'
BACK=`grep "^-backpath$s" ~/.joerc | head -n1`
BACK=`expr x"$BACK" : x"$n*$s\\+\\(.*$n\\)$s*\$" || :`
set sed
if test -n "$BACK"
then
	if test ! -d "$BACK"
	then
		echo "ERROR: Old backup path '$BACK'" \
			"has does not yet exist!" >& 2
		false || exit
	fi
	set "$@" -e "s!^$s*-backpath\\($s.*\\)\\?\$!-backpath $BACK!"
fi
if grep -q '^-nobackups' ~/.joerc
then
	set "$@" -e "s!^$s\\+\\(-nobackups\\($s.*$n\\)\\?\\)$s*\$!\\1!"
fi
FTYPERC=$HOME/.joe
set "$@" -e "s!^:include$s\\+ftyperc$s*\$!:include $FTYPERC!"
"$@" /usr/local/etc/skel/.joerc > ~/.joerc
cp /usr/local/etc/skel/.joe ~/.joe
