#! /bin/sh
# One needs to define a "-backpath", but it does not need
# to actually exist in the filesystem.
#
# Version 12.145
# (c) 2012 by Guenther Brunthaler.
# This source file is free software.
# Distribution is permitted under the terms of the GPLv3.


# Removes trailing and leading tabs and spaces.
trim() {
	local OLD NEW TAB
	OLD=$1
	TAB=`printf '\t'`
	while :
	do
		NEW="${OLD# }"
		NEW=${NEW#$TAB}
		test x"$NEW" = x"$OLD" && break
		OLD=$NEW
	done
	while :
	do
		NEW="${OLD% }"
		NEW=${NEW%$TAB}
		test x"$NEW" = x"$OLD" && break
		OLD="$NEW"
	done
	printf '%s\n' "$NEW"
}


BACK=`grep '^\s*-backpath /.*' ~/.joerc | head -n1`
BACK=${BACK#*backpath}
BACK=`trim "$BACK"`
if test -z "$BACK"
then
	echo "ERROR: No backup path has been set up yet"
	false; exit
fi
if test ! -d "$BACK"
then
	echo "ERROR: Old backup path '$BACK' has does not yet exist!"
	false; exit
fi
NOBACKS=`grep '^\s*-nobackups' ~/.joerc | head -n1`
if test -n "$NOBACKS"
then
	NOBACKS=`
		printf '%s\n' "$NOBACKS" \
			| sed -e 's,^\(\s*\)-nobackups.*,\1,'
	`
else
	# By default, disable "-nobackup" so backups will be made.
	NOBACKS=" "
fi
FTYPERC=$HOME/.joe
sed -e '
	s!^\s*-backpath /.*!-backpath '$BACK'!
	s!^\s*\(-nobackups.*\)!'"$NOBACKS"'\1!
	s!^:include\s\s*ftyperc\s*$!:include '$FTYPERC'!
' /usr/local/etc/skel/.joerc > ~/.joerc
cp /usr/local/etc/skel/.joe ~/.joe
