#! /bin/sh
# Invoke "sed" (passing through any -i option) with predefined string
# transformation which tries to substitute non-LATIN9 UNICODE characters with
# LATIN9 replacement characters. Also, sequences of non-breaking space,
# horizontal tabulation and similar whitespace characters will be replaced by
# a single space character.
#
# Version 2018.235
# Copyright (c) 2017-2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e

cleanup() {
	rc=$?
	test "$FIFO" && rm -- "$FIFO"
	case $rc in
		0) return;;
		126) how="when attempting to run a non-executable file";;
		127) how="because a command was not found";;
		*)
			how="with signal `kill -l $rc 2> /dev/null`" \
			|| how="with return code $rc"
	esac
	echo "$0 failed $how!" >& 2
}
FIFO=
trap cleanup 0
trap 'exit $?' INT TERM QUIT HUP

verify_posint_arg() {
	expr x"$OPTARG" : x'[1-9][0-9]*$' > /dev/null
}

opts=
crad=10 # Context radius.
pos=
while getopts ip:c: opt
do
	case $opt in
		i) opts="$opts -$opt";;
		p) verify_posint_arg; pos=$OPTARG;;
		c) verify_posint_arg; crad=$OPTARG;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

if test "$pos"
then
	test $# = 0 && set /dev/stdin
	cbef=`expr $crad \& $pos \> $crad \| $pos || :`
	cdia=`expr $cbef + $crad`
	rbs=8192
	while test $rbs -lt $cdia
	do
		rbs=`expr $rbs + $rbs`
	done
	bo=`expr $pos - $cbef || :`
	bi=`expr $bo / $rbs || :`; bo=`expr $bo % $rbs || :`
	lb=`
		dd if="$1" bs=$rbs skip=$bi count=1 \
		| dd bs=1 skip=$bo count=$cdia
	` 2> /dev/null
	pfx=`printf '%s\n' "$lb" | dd bs=1 count=$cbef` 2> /dev/null
	echo "<...>$pfx<AFTER_THIS>${lb#"$pfx"}<...>"
	exit
fi

substs=`
iconv -f UTF-7 << 'EOF'
s/+AFsAWw:space:+AF0AoABdAFwAew-1,+AFwAfQ-/ /g
s/+AF4 //
s/ +ACQ-//
s/+ICY-/.../g
s/+IBQ-/ - /g
y/+IDogOQCrALsgHSAcIB4gEyAZIBgAtA-/+ACIAIgAiACIAIgAiACI--'''/
y/+IAY-/ /
y/+A7w-/+ALU-/
y/+AUIBGQEfAQ0BRA-/legcn/
EOF
`

while :
do
	t=`mktemp -u -- "${TMPDIR:-/tmp}/${0##*/}".XXXXXXXXXX`
	mkfifo -m 600 "$t" && break
done
FIFO=$t

{
	{
		sed$opts "$substs" "$@" && :
		echo $? >& 5
	} | {
		iconv -t LATIN9 && :
		echo $? >& 5
	} | {
		iconv -f LATIN9 && :
		echo $? >& 5
	}
} 5> "$FIFO" & pid=$!

children=3
worst=0
while :
do
	read rc
	if test $rc != 0
	then
		if test $worst = 0
		then
			timeout=5
			{
				sleep $timeout
				kill $pid || :
				while :
				do
					sleep 999
				done
			} & timeout=$!
		elif test $rc -le $worst
		then
			continue
		fi
		worst=$rc
	fi
	children=`expr $children - 1` && continue
	break
done < "$FIFO"
test $worst != 0 && kill $timeout || :
wait
