#! /bin/sh
# Works like "man", but displays the "man" page formatted as PostScript.
#
# Version 2018.77
#
# Copyright (c) 2012-2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

T=`mktemp "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`
trap "rm -- \"$T\"" 0
man -t "$@" > "$T" && gv "$T"
