#!/bin/sh
#
# Version 2023.365
# Copyright (c) 2007-2023 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.


die() {
	echo "ERROR: $*" >& 2
	exit 1
}


chk4() {
	command -v "$1" > /dev/null 2>& 1
}


if chk4 ctags; then
	find -type f | xargs \
		ctags -d --globals --members -T --declarations \
			-o tags 2> /dev/null
elif chk4 exuberant-ctags; then
		exuberant-ctags -f tags --recurse
else
	die "No supported ctags utility has been installed!"
fi
