#! /bin/sh
#
# Mount or unmount (toggle) encrypted personal directory.
# Written in 2008 by Guenther Brunthaler.


checkopt() {
	while test $# -gt 0; do
		case $1 in
			-*) ;;
			*) echo "Bad option '$1'!" >& 2; exit 1;;
		esac
		shift
	done
}


checkopt "$@"
exec encfs-mount "$@" --non-empty "$HOME"/p/p2/p3
