#! /bin/sh
# This script can be run from the command line or be executed by a graphical
# file manager. It requires 2 or more PDF files as argument, and appends the
# contents of all the remaining PDFs in the same order to the existing
# contents of the first one.
#
# Version 2016.302
#
# Copyright (c) 2016 Guenther Brunthaler. All rights reserved.
#
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
cleanup() {
	rc=$?
	test -n "$O" && mv -- "$B" "$O"
	test $rc = 0 && return
	msg="$0 failed!"
	xmessage "$msg" || printf '%s\n' "$msg" >& 2
}
O=
trap cleanup 0
trap 'exit $?' QUIT TERM INT HUP

test $# != 0
test $# = 1 && return # Nothing to do.
B=`mktemp -- "$1.original.bak.XXXXXXXXXX"`
mv -- "$1" "$B"
O=$1
shift
gs -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH -q -sDEVICE=pdfwrite \
	-sOutputFile="$O" "$B" "$@"
O=
