#! /bin/sh
# Finds all symbols in all source files containing
# symbol prefix "${1}_" in either letter case.
# This will also match if the symbol is only part
# of a larger symbol (concatenated with an underscore).
SYM=${1?specify a symbol prefix!}
find '(' \
	-name "*.c" -o -name "*.h" \
	-o -name "*.cpp" -o -name "*.hpp" \
	-o -name "*.cxx" -o -name "*.hxx" \
	-o -name "*.C" -o -name "*.inl" \
	')' -type f -print0 \
	| xargs -0 -- perl -ne '
		$sym= quotemeta '"$SYM"';
		while(
			/
				(?: ^ | (?<! [:alnum:] ) )
				(
					(?i: $sym )
					_ [-\w]+
				)
			/gx
		){ print "$1\n" }
	' | LC_ALL=C sort -u
