#! /bin/sh
# Generate a base-64 password: 256 bits without arguments, or 128 bits
# otherwise. May block until enough entropy becomes available in /dev/random.
set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
if ssl=`which openssl 2> /dev/null`
then
	b64() { "$ssl" base64; }
else
	alias b64=base64
fi
bits=256
test $# != 0 && bits=128
dd if=/dev/random bs=1 count=`expr $bits / 8` 2> /dev/null | b64 | tr -d =
