#! /bin/sh
# Version 2018.77
#
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

case `basename -- "$0"` in
	u*) mode=unqote;;
	*) mode=quote
esac
while getopts qu opt
do
	case $opt in
		q) mode=quote;;
		u) mode=unqote;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`
case $mode in
	quote) sx='s/[$`\\"]/\\&/g';;
	unqote) sx='s/\\\([$`\\"]\)/\1/g';;
	*) false || exit
esac
exec sed -- "$sx"
