#!/usr/bin/perl
# Filter to remove trailing whitespace from lines.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/rtrim $
# $Author: root(xvaio) $
# $Date: 2006-10-30T07:48:58.241945Z $
# $Revision: 368 $


while (defined($_= <>)) {
   s/\s*$/\n/;
   print;
}
