#! /usr/bin/perl
# Filter to remove trailing whitespace from lines.
#
# Version 2020.11
# Copyright (c) 2006-2020 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

use strict;
use warnings qw(all);
use autodie;
use open ':locale';
use Getopt::Std;

getopts('') or die;
my $nl;
while (defined($_= <>)) {
   $nl= chomp ? "\n" : "";
   s/\s+$//;
   print "$_$nl" or die $!;
}
STDOUT->flush() or die $!;
