#! /bin/sh
# Prepend the output of this script to a $PRLANG source file and "chmod +x" it.
# The $PRLANG program can then be run as a normal shell script.
#
# Version 2021.30
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

sed '/e?/d; s/$PRLANG/'"${1?"prog. language?"}"'/g; $s/$/\n/' < "$0"
test $# = 2 && test -f "$2" && exec cat < "$2"; # "e?" (exclusion marker)
test -t 0 && exit || exec cat; # "e?" (exclusion marker)
ver=`sed 's/^# Version //; t1; d; :1; q' < "$0"`
sed '1d; s/$'VERSION/$ver'/g; t; /^#!/,$!d; $s/$/\n/' < "$0"
test $# = 1 && test -f "$1" && exec cat < "$1"
test -t 0 && exit || exec cat
