#! /bin/sh

# Version information located farther below.
case $1 in
	fast_cpu_wholefamily) # release (recommended for normal use)
		CFLAGS="-D NDEBUG -O2 -mtune=native"
		LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
		;;
	fastest_cpu_wholefamily) # release
		CFLAGS="-D NDEBUG -O3 -mtune=native"
		LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
		;;
	smallest_cpu_wholefamily) # release
		CFLAGS="-D NDEBUG -Os -mtune=native"
		LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
		;;
	posix) # release (only POSIX-guaranteed options)
		CFLAGS="-D NDEBUG -O"
		LDFLAGS="-s"
		;;
	debug) # debug
		CFLAGS="-O0 -ggdb3"
		LDFLAGS=
		;;
	devel) # debug with maximum warnings and protectors
		CFLAGS="-O0 -ggdb3 -Wall -Wextra -Wpedantic"`:
			`" -D _FORTIFY_SOURCE=2 -fstack-protector-strong"
		LDFLAGS=
		;;
	fastest_cpu_specific) # release
		CFLAGS="-D NDEBUG -O3 -march=native"
		LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
		;;
	smallest_cpu_specific) # release
		CFLAGS="-D NDEBUG -Os -march=native"
		LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
		;;
	gdb)
		alias gdb="gdb -iex 'add-auto-load-safe-path $PWD'"
		;;
	geninit)
		 cat <<- '======' > .gdbinit
file ./sum
b *main
# Example how to set arguments and redirection:
r 1 2 3 > sum_output.txt
# Alternative to redirection in "run" command, also redirects stdin and stderr:
#tty /dev/pts/17
#set directories /basepath/to/src/files
set history size 500
set history save on
set scheduler-locking on
#layout asm
layout src
focus cmd
======
		;;
	mfsimple)
		 cat << '======' > Makefile
.POSIX:

# You may redefine these settings via the "make" command line or export them
# as environment variables and (in the latter case only) also
# "export MAKEFLAGS=e". Or just edit this file.

CFLAGS = -D NDEBUG -O
LDFLAGS = -s

# No need to redefine these.
TARGETS = myprog

.PHONY: all clean

all: $(TARGETS)

clean:
	-rm $(TARGETS)
======
		;;
	mflibs)
		 cat << '======' > Makefile
.POSIX:

# You may redefine these settings via the "make" command line or export them
# as environment variables and (in the latter case only) also
# "export MAKEFLAGS=e". Or just edit this file.
CPPFLAGS = -D NDEBUG
CFLAGS = -O
LDFLAGS = -s

# No need to redefine these.
LIBS = -lm

TARGETS = myprog

.PHONY: all clean

all: $(TARGETS)

clean:  
	-rm $(TARGETS)

AUG_CFLAGS = $(CPPFLAGS) $(CFLAGS)
AUG_LDFLAGS = $(LDFLAGS) $(LIBS)

.c:
	$(CC) $(AUG_CFLAGS) -o $@ $< $(AUG_LDFLAGS)
======
		;;
	reset)
		unset export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS MAKEFLAGS \
			mkfsubst_t2uj0ij0ite58mbuiz6elilzh
		unset -f smf
		unalias gdb 2> /dev/null || :
		return
		;;
	smf)
		smf() {
			export MAKEFLAGS
			if test -z "${1+set}"
			then
				echo "No Makefile substitute has been" \
					"provided."
				echo
				echo "'make' is currently using"
				eval 'echo "'\''${'`:
					`'mkfsubst_t2uj0ij0ite58mbuiz6elilzh'`:
					`'-Makefile}'\'' as its Makefile."'
				echo
				echo "Provide the name of a substitute or an"
				echo "empty string to revert to the default."
				return
			fi
			if test -z "$1"
			then
				# Empty string as argument resets to default.
				set Makefile
			fi
			if
				expr x"$1" : x'[[:alnum:].-_=+:^]\{1,\}$' \
				> /dev/null
			then
				:
			else
				echo "Problematic characters detected in" \
					"pathname of 'Makefile'" \
					"substitute." >& 2
				echo "Please rename!" >& 2
				false || return
			fi
			eval 'echo "So far, '\''make'\'' has been using'`:
				`' '\''${mkfsubst_t2uj0ij0ite58mbuiz6elilzh'`:
				`':=Makefile}'\''"'
			echo "as its Makefile."
			if test "$mkfsubst_t2uj0ij0ite58mbuiz6elilzh" != "$1"
			then
				echo "Now it will be using '$1' instead."
			else
				echo "There is no change."
			fi
			mkfsubst_t2uj0ij0ite58mbuiz6elilzh=$1
			if
				test "$mkfsubst_t2uj0ij0ite58mbuiz6elilzh" \
				= Makefile
			then
				unset mkfsubst_t2uj0ij0ite58mbuiz6elilzh
			fi
			MAKEFLAGS=`
				printf '%s\n' "$MAKEFLAGS" \
				| sed -e 's/[[:space:]]\{1,\}-f[[:space:]]*'\`:
					\`'[^[:space:]]*/ /g' \
					-e 's/[[:space:]]*$//'
			`
			if test "$mkfsubst_t2uj0ij0ite58mbuiz6elilzh"
			then
				MAKEFLAGS="$MAKEFLAGS -f "`:
					`"$mkfsubst_t2uj0ij0ite58mbuiz6elilzh"
			fi
		}
		;;
	help | *)
		echo "${0##*/} Version 2026.35"
		sed 's|^[[:space:]]*\(.*\)) \(#.*\)'`:
			`'|set \1 \&\& . '"${0##*/}"' \&\& make \2|;'`:
			`' t; d' "$0" \
		| while read -r setting
		do
			echo "\$ make clean && $setting"
		done
		echo "\$ set reset && . ${0##*/}" \
			"# reset all customized settings"
		echo "\$ set gdb && . ${0##*/}" \
			"# Define alias 'gdb' which allows gdb to be" \
			"invoked from unsafe '.'"
		echo "\$ set smf && . ${0##*/}" \
			"# Define shell function 'smf'" \
			"which sets a different name for 'make' to use" \
			"instead of 'Makefile'."
		echo "\$ set geninit && . ${0##*/}" \
			"# Create customizable template ./.gdbinit"
		echo "\$ set mfsimple && . ${0##*/}" \
			"# create customizable simple POSIX-compliant Makefile"
		echo "\$ set mflibs && . ${0##*/}" \
			"# create customizable POSIX-compliant Makefile" \
			"using libraries"
		echo "\$ sh ${0##*/} # THIS help"
		return
esac
CFLAGS="$CFLAGS -pipe"
case $* in
	*" -P") MAKEFLAGS=1;; # Set -P as 2nd argument for non-parallel builds.
	*)
		MAKEFLAGS=`
			nproc \
			|| getconf _NPROCESSORS_ONLN 2> /dev/null \
			|| echo 1
		`
		MAKEFLAGS=`expr $MAKEFLAGS + 1`
esac
MAKEFLAGS=-e`
	case $MAKEFLAGS in
		1) exit
	esac
	make --help 2>& 1 \
	| sed 's/^[[:space:]]*-\\([jl]\\)[[:space:]]\\{1,\\}.*/ -\\1'\`:
		\`$MAKEFLAGS'/; t;'\`:
		\`' s/.*[[:space:]]\\{1,\\}\\(--output-sync\\).*/ \\1/;'\`:
		\`' t; d' \
	| paste -sd ''
`
if test "$mkfsubst_t2uj0ij0ite58mbuiz6elilzh"
then
	MAKEFLAGS="$MAKEFLAGS${MAKEFLAGS+ }-f "`:
		`"$mkfsubst_t2uj0ij0ite58mbuiz6elilzh"
fi
# Don't use $CPPFLAGS globally outside of a Makefile. They are not supported
# directly be POSIX "make" and are therefore dangerous. Use $CFLAGS instead
# for the same purposes.
export CPPFLAGS= CFLAGS LDFLAGS MAKEFLAGS
unset CXXFLAGS
