#! /bin/sh
# Copyright (c) 2016 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.
set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
case $# in
	0)
		end='s/.*[^0-9]\([0-9]\{2\}\)h\([0-9]\{2\}\)$/\1:\2/'
		msg=$0
		;;
	1 | 2)
		end='s/^\([0-9]\{2\}\)[h:]\([0-9]\{2\}\)$/\1:\2/'
		case $# in
			1) msg=$1;;
			*) msg=`printf %02u:%02u "$1" "$2"`
		esac
		;;
	*) false || exit
esac
msg=`printf '%s\n' "$msg" | sed "$end"`
today=`date -d "$msg" +%s`
now=`date +%s`
if test $now -lt $today
then
	end=$today
else
	msg="tomorrow $msg"
	end=`date -d "$msg" +%s`
fi
duration=`expr $end - $now || :`
echo "Sleeping until $msg ($duration seconds)..."
exec sleep $duration
