#! /bin/sh
# Filter replacing runs of empty lines (or lines containing only whitespace)
# by single empty lines. Also removes all empty lines (or lines containing
# only whitespace) from the beginning and end.
#
# Version 2020.340
# Copyright (c) 2020 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

sed 's/^[[:space:]]*$//' | {
	initial=true
	delayed=false
	while IFS= read line
	do
		case $line in
			'') delayed=true;;
			*)
				case $delayed in
					true)
						case $initial in
							true) initial=false;;
							*) echo
						esac
						delayed=false
				esac
				printf '%s\n' "$line"
		esac
	done
}
