#! /bin/sh
# Launches a virtual frame-buffer X11 server, to be
# controlled with vncviewer of the TightVNC package
# either locally or via an SSH tunnel.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/start-virtual-xserver $
# $Author: root $
# $Date: 2007-05-14T17:26:48.671994Z $
# $Revision: 683 $


usage() {
	cat <<- "."
	start-virtual-xserver - start virtual X server for SSH/TightVNC
	
	Usage: start-virtual-xserver [options]
	
	options:
	--size <WxH>, s <WxH>:
	  Specify width and height of the virtual display
	  in pixels. Defaults to 1024x768.
	--depth <bits>, -d <bits>:
	  Bit-depth of the virtual display. Defaults to 24.
	--help, -h: Display this help text.
	--verbose, -v: Verbose operation.
	--dry-run, --simulate, -n:
	  Just print what would be done, but don't actually
	  do anything.

	Version 10.124
	Written by Guenther Brunthaler in 2007 - 2010.
.
}
                                                                                                                             

die() {
	{
		echo "ERROR: $*"
		echo "Use $0 --help for help."
	} >& 2
	exit 1
}
                                                        

# Start of command line processing.
# Define presets.
VERBOSE=0
DRY=0
SIZE=1024x768
DEPTH=24
#
COPTS=
while true; do
	if [ -z "$COPTS" ]; then
		case "$1" in
			-?*) COPTS="$1"; shift;;
			*) break;;
		esac
	fi
	if [ "${COPTS#--}" = "$COPTS" ]; then
		TAIL="${COPTS#-?}"; # Switch clustering.
		COPT="${COPTS%$TAIL}"; COPTS="${TAIL:+-}$TAIL"
	else
		COPT="$COPTS"; COPTS=
	fi
	# Any arguments are at $1 and onwards; must be shifted off.
	case "$COPT" in
		--) break;; # Must be first!
                --help | -h) usage; exit;;
		--version)
			# Sychronize this with the usage text!
			echo "Version 1.0"
			exit;;
		--verbose | -v) VERBOSE=1;;
		--dry-run | --simulate | -n) DRY=1;;
		--size | -s) SIZE="$1"; shift;;
		--depth | -d) SIZE="$1"; shift;;
		*) die "Unknown option '$COPT'!";; # Must be last!
	esac
done
# Shift off ordinal arguments.
#test $# -ge 1 && { WORKDIR="$1"; shift; }
#test $# -ge 1 || die "Missing argument - limit for accumulated sum!"
#LIMIT="$1"; shift
# Check for excess arguments.
test $# = 0 || die "Unexpected excess arguments: $*"
# End of command line processing.
CPFX=
test $DRY = 1 && CPFX=echo
echo "Launching virtual X11-Server ($SIZE with 2 ** $DEPTH colors)."
$CPFX vncserver -geometry $SIZE -depth $DEPTH -localhost -nolisten tcp
echo "Now set your \$DISPLAY variable accordingly!"
echo "For instance, if the above lines said"
echo ">>>New 'X' desktop is hostname:1<<<"
echo "then enter the following commands now:"
echo '$ DISPLAY=:1'
echo '$ export DISPLAY'
echo "This will allow you to launch X applications on the virtual server"
echo "from the command line, such as"
echo '$ xclock&'
echo '$ xterm&'
echo
echo "Hint: If you want to control your shiny little frame-buffer server"
echo "with TightVNC's 'vncviewer' through an SSH tunnel, be sure to connect"
echo "to this machine with a statement like"
echo '$ ssh -L5900:localhost:5901 user@host'
echo "where the '5901' equates 5900 + the number in \$DISPLAY,"
echo "i. e. the '1' in ':1'."
echo
echo "Also consider running the script"
echo '$ tightvnc-via-local-ssh-forwarding'
echo "instead of running 'vncviewer' directly, which invokes"
echo "vncviewer with suitable parameters for JPEG-compression and"
echo "SSH tunneling."
