#! /bin/sh
# Version 2018.207.1
#
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

cookies=~/.surf/cookies.txt

# Options enabled/set:
#
# -a '@' Reject third-party cookies
# -k not kiosk-mode
# -f not fullscreen mode
# -g disable geolocation
# -i disable image loading
# -p disable PlugIns (sch as JAVA applet support)
# -s disable JavaScript
#
# Options which might seem to be useful, but aren't because new tabs won't
# inherit them:
#
# -z 1.5 Zoom level
# -m disable user stylesheets
# -d disable disk cache
#
# The WebInspector is left enabled because it costs neglectible RAM as long as
# it is not actually being used.
surf_options='-a @ -kfgips'

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

mkdir -p -- "`dirname -- "$cookies"`"
> "$cookies" # Remove all cookies from the last session.

test $# = 0 && set file:///
tabbed -c -r 2 surf -e '' $surf_options -c "$cookies" -- "$@" \
	< /dev/null > /dev/null 2>& 1 &
if test -t 1
then
	cat << EOF
The most important shortcuts:

[Shift]+[Ctrl]+[Return] or middle-clicking on link opens a new tab
[Ctrl]+[q] closes current tab (middle-clicking on a tab also closes it)
[Ctrl]+[g] prompts for URL
[Esc] stop loading current page
[Ctrl]+[r] reload page

[Ctrl]+[y] copy URI
[Shift]+[Ctrl]+[i] enables/toggles auto image loading
[Shift]+[Ctrl]+[s] enables/toggles JavaScript
[Shift]+[Ctrl]+[v] enables/toggles plugins
[Shift]+[Ctrl]+[o] examine current web page
[Ctrl]+[o] show source code of current web page
[F11] toggle full-screen mode

See "man tabbed" and "man surf" for more keyboard shortcuts.
EOF
fi
