#! /bin/sh
# Finds all symbols in all source files containing
# symbol $1 in any letter case.
SYM=${1?specify a symbol prefix!}
find '(' \
	-name "*.c" -o -name "*.h" \
	-o -name "*.cpp" -o -name "*.hpp" \
	-o -name "*.cxx" -o -name "*.hxx" \
	-o -name "*.C" -o -name "*.inl" \
	')' -type f -print0 \
	| xargs -0 -- perl -ne '
		$sym= quotemeta '"$SYM"';
		while (/ \b (?i: ($sym) ) \b /gx) { print "$1\n" }
	' | LC_ALL=C sort -u
