#! /bin/sh
# Finds all symbols in all source files containing
# symbol $1 in any letter case.
SYM=${1?specify a symbol!}
find-c-and-cpp-sources-files -0 \
	| xargs -0 -- perl -ne '
		$sym= quotemeta '"'$SYM'"';
		while (/ \b (?i: ($sym) ) \b /gx) { print "$1\n" }
	' -- | LC_ALL=C sort -u
