#! /bin/sh

# Filter to titlecase words (convert first character of words to uppercase).
#
# Version 2025.360
# Copyright (c) 2006-2025 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

if test -t 0
then
	cg | "$0" | cs; exit
fi
exec perl -x -S -- "$0"; exit

#! perl
#line 19

use strict;
use warnings qw(all);
use autodie;
use open ':locale';
use Getopt::Std;

getopts('') or die;
my $nl;
while (defined($_= <>)) {
   $nl= chomp ? "\n" : "";
   s/\b(.)/\u$1/g;
   print "$_$nl" or die $!;
}
STDOUT->flush() or die $!;
