#! /bin/sh
# Run a shell in a temporary directory to be removed when the shell exits.

set -e
cleanup() {
	local rc=$?
	cd
	test -n "$T" && rm -rf -- "$T"
	test $rc = 0 || echo "$APP failed!" >& 2
}
APP=${0##*/}
T=
trap cleanup 0
T=`mktemp -d "${TMPDIR:-/tmp}/$APP.XXXXXXXXXX"`
echo "Entering temporary shell directory '$T'." >& 2
export d=`pwd`
echo "The original current directory is available as \$d." >& 2
echo "Enter 'exit' to leave and remove temporary directory." >& 2
cd "$T"
PS1='\u@\h [tmpshell] \$ ' # Most likely, this will be overwritten anyway.
export PS1
MYSH=${SHELL:-/bin/sh}
test -x "$MYSH"
"$MYSH"
echo "Removing temporary shell directory '$T'." >& 2
