#! /bin/sh
# Run a shell in a temporary directory to be removed when the shell exits.
# Version 2019.320

set -e
cleanup() {
	rc=$?
	cd
	test -n "$T" && rm -rf -- "$T"
	test $rc = 0 || echo "$APP failed!" >& 2
}
APP=${0##*/}
T=
trap cleanup 0
T=`mktemp -d "${TMPDIR:-/tmp}/$APP.XXXXXXXXXX"`
echo "Entering temporary shell directory '$T'." >& 2
export p=`pwd`
echo "The previous current directory is available as \$p." >& 2
echo "Enter 'exit' to leave and remove temporary directory." >& 2
cd "$T"
PS1='\u@\h [tmpshell] \$ ' # Most likely, this will be overwritten anyway.
export PS1
case ${SHELL:=/bin/sh} in
	/*) ;;
	*) SHELL=`command -v -- "$SHELL"`
esac
test -x "$SHELL"
"$SHELL" -l
echo "Removing temporary shell directory '$T'." >& 2
