#! /bin/sh
# Displays the combined up- and download byte count on the specified interface
# (defaults to ppp0) since the interface was brought up.

PATH=/sbin:/usr/sbin:$PATH
LC_ALL=C ifconfig ${1:-ppp0} | perl -ne '
	BEGIN {
		$b= 0;
	}
	if (/RX[^0-9]*([0-9]*).*TX[^0-9]*([0-9]*)/) {
		$b= $1 + $2;
	} elsif (/\s[RT]X packets\s.*\sbytes\s*(\d+)/) {
		$b+= $1;
	}
	END {
		$mb= 1024 ** 2;
		printf "%.2f MiB\n", $b / $mb;
	}
'
