#!/usr/bin/perl
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/ucase $
# $Author: root(xvaio) $
# $Date: 2006-08-27T11:02:50.623454Z $
# $Revision: 254 $


while (defined($_= <>)) {
   print uc;
}
