#! /bin/sh
exit_version() {
	wr -s << ===; exit
$APP Version 2020.138
Copyright (c) 2019-2020 Guenther Brunthaler. All rights reserved.

This script is free software.
Distribution is permitted under the terms of the GPLv3.
===
}

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0

exit_help() {
	wr << ===
$APP - undo the effect of a "fold" with "-s" option.

Usage: $APP [ <options> ... ] [ -- ] [ <file1> ... ]

Be sure not to disturb any space immediately before newlines! If those spaces
should be removed, a lossless back-transformation is no longer possible.

Editors such as "joe" have explicit options for editing such files. For
instance, this can be used to edit a text with very long lines like this:
===
	echo; cat << ===
\$ fold -sw 72 long_lines.txt > rfc3676-flowed.txt
\$ joe -flowed -wordwrap -rmargin 72 rfc3676-flowed.txt
\$ $APP rfc3676-flowed.txt > long_lines.txt
\$ rm rfc3676-flowed.txt
===
	echo; wr << ===; echo; exit_version
The above example assumes you want to temporarily break lines at 72 columns
during editing, because this is the traditional line width for e-mail. Feel
free to use other line widths, such as 66 for optimal reading experience or 79
for maximally exploiting the available screen width of an 80-column terminal.

See https://tools.ietf.org/rfc/rfc3676.txt for details about the type of text
which has been created by "fold -s", and which $APP expects as input.

Options:

-h: Display this help and exit.

-V: Display version information and exit.
===
}

wr() {
	if test "$*"
	then
		fold -sw $LINEWIDTH | sed 's/[[:space:]]*$//'
	else
		{
			sep=
			while IFS= read -r line
			do
				printf %s%s "$sep" "$line"
				if test "$line"
				then
					sep=' '
				else
					echo
					test -z "$sep" && continue
					echo; sep=
				fi
			done
			test -z "$sep" || echo
		} | wr -s
	fi
}
LINEWIDTH=`
	cmd=tput; command -v $cmd > /dev/null 2>& 1 \
	&& test -t 0 && $cmd cols \
	|| echo 66
`

APP=${0##*/}
while getopts Vh opt
do
	case $opt in
		h) exit_help;;
		V) exit_version;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

q=56f5h41cb63i5ngjf3ilv9quk
sed "s/Q/$q/g;"' s/$/Q/; s/ Q$/ /' ${1+"$@"} \
| tr -d \\n | tr Q \\n \
| sed "s/$q/Q/g"
