#! /bin/sh
# Pipe the unpacked package list to this running script.
#
# Create the list by installing into a stage directory,
# then changing to it, then running "find -depth" from there.
#
# Finally, install the files from the staging dir into
# the live file system via
#
# $ rsync -pvrl /path/to/staging/dir/home/$USER/ /home/$USER/
set -e
trap "echo 'Failed!'" 0
cd /
while IFS= read -r LINE
do
	test x"$LINE" = x"." && continue
	test x"${LINE#./}" != x"$LINE" || {
		echo "All lines need to start with './'!" >& 2
		false; exit
	}
	if test ! -L "$LINE" && test -d "$LINE"
	then
		rmdir -- "$LINE" || true
	elif test -e "$LINE"
	then
		rm -- "$LINE" || {
			echo "Could not delete '/$LINE'!" >& 2
			false
		}
	fi
done
trap - 0
echo "Uninstallation complete."
