#! /usr/bin/perl -w
#
# Convert formatted text to free flowing text. Assume empty lines to separate
# paragraphs. Also every line starting with most special characters is
# considered a paragraph, unless the line before it contains whitespace at its
# end, in which case it is assumed to be just another continuation line.
#
# Version 16.319
#
# Copyright (c) 2007-2016 Guenther Brunthaler. All rights reserved.
# 
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.

use locale;

my $o= '';
while (defined($_= <>)) {
   chomp;
   s/^\s+$//; # Lines only containing whitespace are always considered empty.
   if (s/\s+$//) {
      # RFC 3676 indication of being followed with a continuation line.
      s/\s+/ /g; # Merge multiplace whitespace.
      s/^ //; # Remove any leading space.
      $o.= " " if $o ne '' && length;
      $o.= $_;
      next;
   }
   if (!length || /^[^"'([{[:alnum:]]|^(-|[.]{2,})\s/) {
      # Assume this starts a new paragraph.
      print "$o\n" if $o ne '';
      print "$_\n";
      $o= '';
   } else {
      $o.= " " if $o ne '';
      $o.= $_;
   }
}
print "$o\n" if $o ne '';
