#! /bin/sh

# Convert formatted text to free-flowed text. Assume empty lines to separate
# paragraphs. Also every line starting with most special characters is
# considered a paragraph, unless the line before it contains whitespace at its
# end, in which case it is assumed to be just another continuation line.
#
# Version 2025.360
# Copyright (c) 2007-2025 Guenther Brunthaler. All rights reserved.
# 
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.

if test -t 0
then
	cg | "$0" | cs; exit
fi
exec perl -x -S -- "$0"; exit

#! perl
#line 22

use strict;
use warnings qw(all);
use autodie;
use open ':locale';
use Getopt::Std;
use locale;

sub pr(@) {
   print @_ or die $!;
}

getopts('') or die;
my $o= '';
while (defined($_= <>)) {
   chomp;
   s/^\s+$//; # Lines only containing whitespace are always considered empty.
   if (s/\s+$//) {
      # RFC 3676 indication of being followed with a continuation line.
      s/\s+/ /g; # Merge multiplace whitespace.
      s/^ //; # Remove any leading space.
      $o.= " " if $o ne '' && length;
      $o.= $_;
      next;
   }
   if (!length || /^[^"'([{[:alnum:]]|^(-|[.]{2,})\s/) {
      # Assume this starts a new paragraph.
      pr "$o\n" if $o ne '';
      pr "$_\n";
      $o= '';
   } else {
      $o.= " " if $o ne '';
      $o.= $_;
   }
}
pr "$o\n" if $o ne '';
STDOUT->flush() or die $!;
