#!/bin/sh
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/vmware $
# $Author: root $
# $Date: 2007-05-30T19:25:04.775608Z $
# $Revision: 753 $


case "$1" in
	start|stop|status|restart|reload|zap|pause|ineed|iuse)
		/etc/init.d/vmware-server "$@"
		;;
	*)
		if [ \
			$(
				rc-status --nocolor \
					| grep vmware-authd.*started | wc -l
			) = 0 \
		]; then
			echo "The vmware services are not running!"
			exit 1
		fi
		# Run it niced because the client freaks out
		# if no remote connection is possible and
		# stalls at 100 % CPU load.
		echo "Running vmware console client as background process."
		echo
		echo "Be warned: The vmware client is known to freak out"
		echo "if a requested remote connection fails to be"
		echo "established."
		nice /opt/vmware/server/bin/vmware "$@" &> /dev/null < /dev/null &
		echo "In the case of such an event, enter the command"
		echo "$ ps"
		echo "and look up the process id of the 'vmware' process."
		echo "Then use the 'kill' command to silence that little berserk."
esac
