#! /bin/sh


die() {
	echo "ERROR: $*" >& 2
	exit 1
}


run() {
	"$@" && return
	die "Could not execute >>>$*<<<: return code ${?}!"
}


wrout() {
	if test $# = 0; then
		run fmt -w "`tput cols`"
	else
		run printf '%s\n' "$*" | wrout
	fi
}


show_usage() {
	APP=${0##*/}
	cat <<- EOT | wrout | less -F
	$APP - run mplayer for playing back DVD rips
	
	$APP runs mplayer with suitable options to play back DVD rips
	using a specific audio track and volume boost setting.

	This will be especially important when playing back multiple
	VOB files, because it guarantees the same audio settings are
	used for all the VOB parts of the movie.

	Usage: $APP [ options ... ] [ <file_1.VOB> <file_2.VOB> ... ]
		
	where
	
	<file_1.VOB> <file2_VOB> ...: The VOB files to be played back.
	Defaults to *.VOB, i. e. play back all the VOB files in the current
	directory.
	
	-a <id>, --audio-track <id>: Select audio track <id> for all tracks.
	Defaults to 129.

	-b <n>, --volume-boost <n>, --boost <n>: Set the boost for automatic
	volume boost. It will make the volume louder and automatically keep
	it at about the same volume level throughout the movie. 0 disables
	the feature. Defaults to 20.

	--help, -h: Show this usage help.
	
	$APP (c) 2008 by Guenther Brunthaler
EOT
}


AUDIOLANG=
VOLUMEBOOST=
#
COPTS=
while true; do
	if [ -z "$COPTS" ]; then
		case "$1" in
			-?*) COPTS="$1"; shift;;
			*) break;;
		esac
	fi
	if [ "${COPTS#--}" = "$COPTS" ]; then
		TAIL="${COPTS#-?}"; # Switch clustering.
		COPT="${COPTS%$TAIL}"; COPTS="${TAIL:+-}$TAIL"
	else
		COPT="$COPTS"; COPTS=
	fi
	# Any arguments are at $1 and onwards; must be shifted off.
	case "$COPT" in
		--) break;; # Must be first!
                --help | -h) show_usage; exit;;
		--version)
			# Sychronize this with the usage text!
			echo "Version 1.0"
			exit;;
		-a | --audio-track) AUDIOLANG="$1"; shift;;
		-b | --volume-boost | --boost) VOLUMEBOOST="$1"; shift;;
		*) die "Unknown option '$COPT'!";; # Must be last!
	esac
done
test -z "$*" && set -- *.VOB
mplayer -af volume="${VOLUMEBOOST:-20}:1" -aid "${AUDIOLANG:-129}" "$@"
