#!/bin/sh
# Converts a text file from Windows charset to UTF-8.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/win2utf8 $
# $Author: root(xvaio) $
# $Date: 2006-08-27T11:02:50.623454Z $
# $Revision: 254 $


FROM="WINDOWS-1252"
INTO="UTF-8"


die() {
	echo "ERROR: $1" > /dev/stderr
	exit 1
}


cleanup() {
	rm "$TF" || die "Cannot remove temporary file '$TF'!"
}


# Assign time from $1 as the new time of $2.
copytime() {
	touch -r "$1" "$2" || {
		die "Cannot restore date/time for '$2'!"
	}
}


test $# = 1 || die "Invalid number of arguments!"
F="$1"
test -f "$F" || die "Specify a text file to be converted!"
TF="$F.tmp.$$"
test -e "$TF" && die "Temporary file '$TF' already exists!"
iconv -s -f "$FROM" -t "$INTO" "$F" > "$TF" || {
	# Perhaps it's already converted?
	iconv -s -f "$INTO" -t "$FROM" "$F" > "$TF" || {
		# Neither that is possible.
		cleanup
		die "Could not convert '$F' from $FROM into $INTO!"
	}
	# Silently ignore files which are already converted.
	cleanup
	exit 0
}
if cmp -s "$F" "$TF"; then
	# Conversion resulted in no change.
	cleanup
	exit 0
fi
copytime "$F" "$TF"
cat "$TF" > "$F" || {
	die "Cannot load new contents for '$F' from '$TF'!"
}
copytime "$TF" "$F"
cleanup
