#! /bin/sh
# Use this if "ssh -XY" does not work. Run it with "&" in the background.
# Works on Linux only. When running from within a root jail from where the
# real X11-server has not been started, use -f to bypass some checks which
# would make the script fail.
#
# Version 2020.29
#
# Copyright (c) 2017-2020 Guenther Brunthaler. All rights reserved.
#
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.
DISPLAY_OFFSET=10
PORT_BASE=6000
LOCAL=127.0.0.1
#
set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

force=false
while getopts f opt
do
	case $opt in
		f) force=true;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

test -n "$DISPLAY"
# DISPLAY=hostname:displaynumber.screennumber
# Both numbers may contain leading zeros.
ld=${DISPLAY#:}
if sn=`expr x"${ld}z" : x'[0-9]\{1,\}\.\([0-9]\{1,\}z\)$'`
then
	if sn=`expr ${sn%z} + 0`
	then
		sn=.$sn
	else
		sn=
	fi
fi
ld=`expr "a${ld}" : '\(a[0-9]\{1,\}\)\(\.[0-9]\{1,\}\)\{0,1\}$'`
ld=`expr ${ld#a} + 0 || :`
# Linux specific: start.
ls=/tmp/.X11-unix/X$ld$sn
if $force
then
	:
else
	test -S "$ls"
fi
ls=ABSTRACT:$ls
# Linux specific: end.
rd=`expr $ld + $DISPLAY_OFFSET || :`
rp=`expr $rd + $PORT_BASE || :`
cat << EOF
Process $$: Redirect X11 access from remotehost to local X11 display.

you@here \$ ssh -R $LOCAL:$rp:$LOCAL:$rp user@remotehost
user@remotehost \$ export DISPLAY=$LOCAL:$rd

Don't forget to kill this process once the SSH session is over!
EOF
exec socat TCP4-LISTEN:$rp,bind=$LOCAL,fork,reuseaddr "$ls"
