#! /bin/sh
size=50

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

if test $# = 1
then
	expr x"$1" : x'[1-9][0-9]*$' > /dev/null
	size=$1
fi

cd /
xclock > /dev/null 2>& 1 < /dev/null \
	-digital -update 1 -strftime %T -face "Times New Roman-$size" &
