#! /bin/sh
# Display a nice slideshow using the "xv" tool; can be used either alone
# or as an "xscreensaver"-plugin.
#
# In order to install this as a plugin for xscreensaver, edit your
# $HOME/.xscreensaver file, locate the "programs:" entry, and add a
# line like the following there:
# default-n: "Simple Slideshow" xscreensaver-slideshow -root \n\
# (but without the comment-character "#", of course!)
#
# Before this, however, run this script directly and specify the
# base directory where your images can be found as the only argument.
# The script will then remember this directory, and you won't have
# to specify it for later invocations.
#
# Then select the "Simple Slideshow" screensaver module through
# the xscreensaver-demo GUI.
#
# (c) 2010 by Guenther Brunthaler.
# This script file is free software.
# Distribution is permitted under the terms of the GPLv3.
                 

die() {
	echo "ERROR: $*" >& 2
	false; exit
}


run() {
	"$@" && return
	die "Command >>>$*<<< failed with return code ${?}!"
}


termhandler() {
	test -n "$WORKER" && {
		kill $WORKER
		wait
		exit
	}
	TERMREQ=Y
}


TERMREQ=
WORKER=
trap termhandler SIGTERM SIGINT
CONF=${XDG_CONFIG_HOME:-$HOME/.config}
test -d "$CONF" || run mkdir -p "$CONF"
CONF=$CONF/${0##*/}_6n2rztqe2sywyhxii4ltrmggt.conf
ROOTWINDOW=
DELAY=
while :
do
	case $1 in
		-root) ROOTWINDOW=Y;;
		-delay) DELAY=$2; shift;;
		*) break;;
	esac
	shift
done
PICTURES=$1; shift
DIRTY=Y
{ test -z "$PICTURES" || test -z "$DELAY"; } && test -f "$CONF" && {
	IFS= read -r REPLY < "$CONF"
	DELAY2=${REPLY%% *}
	PICTURES2=${REPLY#* }
	test -z "$PICTURES" && PICTURES=$PICTURES2
	test -z "$DELAY" && DELAY=${DELAY2:-10}
	test x"$PICTURES" = x"$PICTURES2" && test x"$DELAY" = x"$DELAY2" \
		&& DIRTY=
}
test -n "$PICTURES" && test -d "$PICTURES" && test $# = 0 \
	|| die "Usage: ${0##*/} [ -root ] [ -delay N ] <image_directory>"
test -n "$DIRTY" && run printf '%u %s\n' "$DELAY" "$PICTURES" > "$CONF"
run cd "$PICTURES"
set -- xv
test -n "$ROOTWINDOW" && set -- "$@" -rmode 5
set -- "$@" -random -maxpect -viewonly -wloop
set -- "$@" -wait "$DELAY" -flist /dev/stdin
run find -iname '*.jpg' -o -iname '*.png' | "$@" & WORKER=$!
test -n "$TERMREQ" && kill $$
wait
