#! /bin/sh
# Filter for safely encoding / decoding a binary stream.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/bin/xworld-stdcrypt $
# $Author: root(xtreme) $
# $Date: 2006-09-26T04:16:23.581202Z $
# $Revision: 306 $


die() {
	{
		echo "ERROR: $*" >& 2
		echo "Usage: $0 ( -e | -d )" "( <passfile> |" \
			"5< /path/to/passfile" \
			"6< /path/to/passfile" \
			"7< /path/to/passfile" \
			"8< /path/to/passfile)"
	} >& 2
	false; exit
}


run() {
	"$@" && return
	die "Command >>>$*<<< failed with return code ${?}!"
}


crypt() {
	local FD MODE ALGO
	FD=$1 MODE=-$2; ALGO=$3
	set -- openssl "$ALGO" -salt -bufsize 10000000 -pass
	if test -n "$PASSFILE"
	then
		set -- "$@" file:"$PASSFILE"
	else
		set -- "$@" fd:$FD
	fi
	run "$@" "$MODE"
}


ENCRYPT=
while true; do
	case "$1" in
		-e | --encrypt) ENCRYPT=1;;
		-d | --decrypt) ENCRYPT=0;;
		--) shift; break;;
		-*) die "Unknown option '$1'!";;
		*) break;;
	esac
	shift
done
PASSFILE="$1"; shift
test $# = 0 || die "Excess arguments: '$*'"
if test -n "$PASSFILE"
then
	test -f "$PASSFILE" || die "Password file '$PASSFILE' does not exist!"
fi
test -n "$ENCRYPT" || die "Unspecified operation mode!"
if [ $ENCRYPT = 1 ]; then
	crypt 5 e aes-256-cbc | crypt 6 e idea-cbc | crypt 7 e rc4 | crypt 8 e bf-cbc
else
	crypt 8 d bf-cbc | crypt 7 d rc4 | crypt 6 d idea-cbc | crypt 5 d aes-256-cbc
fi
