#! /bin/sh
# Synthesizes local IP addresses from FQDNs as used in xworld domain.
#
# (c) 2012 by Guenther Brunthaler.
# This source file is free software.
# Distribution is permitted under the terms of the GPLv3.


s2md5uc() {
	printf '%s' "$1" | md5sum -b | cut -c-32 | awk '{print toupper($0)}'
}


while :
do
	fqdn=${1:?Usage: ${0##*/} <fqdn> ...}
	host_name=${fqdn%%.*}
	if test x"$host_name" = x"$fqdn"
	then
		network_name=
	else
		network_name=${fqdn#*.}
	fi
	host_id=`s2md5uc "$host_name"`
	network_id=`s2md5uc "$network_name"`
	x_y_z=`
		dc -e "
			1 16 i $network_id FE % + n
			[.] n 1 $host_id FFFE % + d 100 / n
			[.] n 100 % n
		"
	`
	printf '10.%s\t%s\n' $x_y_z "$fqdn"
	shift
	test $# = 0 && break
done
